// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	public "github.com/guojia99/cubing-pro/backend/api/internal/handler/public"
	user "github.com/guojia99/cubing-pro/backend/api/internal/handler/user"
	"github.com/guojia99/cubing-pro/backend/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenInterceptor},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/players",
					Handler: public.PlayersHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v3/public_result"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v3/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserAuthMiddleware, serverCtx.UserLevelMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/id/:userId",
					Handler: user.UserDetailHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v3/user"),
	)
}
