// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
}

type LoginResp struct {
}

type PlayersReq struct {
}

type PlayersResp struct {
}

type RegisterReq struct {
}

type RegisterResp struct {
}

type UserDetailReq struct {
}

type UserDetailResp struct {
}
