// Code generated by goctl. DO NOT EDIT.
package types

type PublicUser struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	MyId         string `json:"myId"`
	WcaId        string `json:"wcaId"`
	Online       int    `json:"online"`
	Sign         string `json:"sign"`
	Avatar       string `json:"avatar"`
	CoverPhoto   string `json:"coverPhoto"`
	Level        uint   `json:"level"`
	DelegateName string `json:"delegateName"`
}

type AuthUser struct {
	PublicUser
	LoginId            string `json:"loginId"`
	HasInitPassword    bool   `json:"hasInitPassword"`
	LoginTime          string `json:"loginTime"`
	LoginIp            string `json:"loginIp"`
	ActivationTime     string `json:"activationTime"`
	BanReason          string `json:"banReason"`
	SumPasswordWrong   string `json:"sumPasswordWrong"`
	PassWordLockTime   string `json:"passWordLockTime"`
	LastUpdateNameTime string `json:"lastUpdateNameTime"`
	Experience         int    `json:"experience"`
	QQ                 string `json:"qq"`
	QQunitID           string `json:"qQunitId"`
	Wechat             string `json:"wechat"`
	WechatUnitID       string `json:"wechatUnitId"`
	ActualName         string `json:"actualName"`
	Sex                int    `json:"sex"`
	Phone              string `json:"phone"`
	Email              string `json:"email"`
	Nationality        string `json:"nationality"`
	Province           string `json:"province"`
	Brithdate          string `json:"brithdate"`
	IDCard             string `json:"idCard"`
	Address            string `json:"address"`
}

type AuthCodeReq struct {
	Ip string `json:"ip"`
}

type AuthCodeResp struct {
	GenerallyResp
	Timeout   int64  `json:"timeout"`
	MdCode    string `json:"mdCode"`
	CodeImage string `json:"codeImage"` // base64
}

type LoginReq struct {
	UserName  string `json:"userName"`  // 用户名
	Password  string `json:"password"`  // 密码
	Timestamp int64  `json:"timestamp"` // 客户端时间戳
	Ip        string `json:"ip"`        // Ip地址
	MdCode    string `json:"mdCode"`    // 获取校验码的数据
	AuthCode  string `json:"authCode"`  // 验证码
}

type LoginResp struct {
	GenerallyResp
	Refresh string `json:"refresh"`
	Token   string `json:"token"`
	Timeout int64  `json:"timeout"`
}

type RegisterReq struct {
	LoginReq
	MyID    string `json:"myId"`
	LoginID string `json:"loginId"`
	QQ      string `json:"qq"`
}

type RegisterResp struct {
	GenerallyResp
	Refresh string `json:"refresh"` // 长期刷新秘钥
	Token   string `json:"token"`
	Timeout int64  `json:"timeout"`
}

type RefreshToeknReq struct {
	Refresh string `json:"refresh"`
}

type RefreshToeknResp struct {
	Token   string `json:"token"`
	Timeout int64  `json:"timeout"`
}

type Role struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	ModifierId string `json:"modifierId"`
}

type Rule struct {
	Id         int64  `json:"id"`
	Code       uint   `json:"code"`
	Name       string `json:"name"`
	CreateId   string `json:"createId"`
	ModifierId string `json:"modifierId"`
	Url        string `json:"url"`
	Option     string `json:"option"`
}

type RoleListReq struct {
	GenerallyListReq
}

type RoleListResp struct {
	GenerallyListResp
	Roles []Role `json:"roles"`
}

type CreateRoleReq struct {
	Role Role `json:"role"`
}

type CreateRoleResp struct {
	GenerallyResp
}

type DeleteRoleReq struct {
	RoleId int64 `path:"roleId"`
}

type DeleteRoleResp struct {
	GenerallyResp
}

type UpdateRoleReq struct {
	RoleId int64 `path:"roleId"`
	Role   Role  `json:"role"`
}

type UpdateRoleResp struct {
	GenerallyResp
}

type RoleBindUsersReq struct {
	RoleId int64 `path:"roleId"`
}

type RoleBindUsersResp struct {
	GenerallyListResp
	Users []AuthUser `json:"users"`
}

type BindRoleReq struct {
	RoleId int64  `path:"roleId"`
	UserID string `json:"userId"`
}

type BindRoleResp struct {
	GenerallyResp
}

type UnbindRoleReq struct {
	RoleId int64  `path:"roleId"`
	UserID string `json:"userId"`
}

type UnbindRoleResp struct {
	GenerallyResp
}

type RoleRulesReq struct {
	GenerallyListReq
	RoleId int64 `path:"roleId"`
}

type RoleRulesResp struct {
	GenerallyListResp
	Rules []Rule `json:"rules"`
}

type AddRulesReq struct {
	RoleId int64 `path:"roleId"`
}

type AddRulesResp struct {
	GenerallyResp
}

type DeleteRulesReq struct {
	RoleId int64 `path:"roleId"`
	RuleId int64 `path:"ruleId"`
}

type DeleteRulesResp struct {
	GenerallyResp
}

type UpdateRulesReq struct {
	RoleId int64 `path:"roleId"`
	RuleId int64 `path:"ruleId"`
	Rule   Rule  `json:"rule"`
}

type UpdateRulesResp struct {
	GenerallyResp
}

type GenerallyResp struct {
	Message string `json:"message"`
	Status  string `json:"status"`
	Code    int64  `json:"code"`
}

type GenerallyListReq struct {
	Page      int64  `form:"page"`
	Size      int64  `form:"size"`
	Search    string `form:"search"`    // 搜索内容
	SearchMap string `form:"searchMap"` // 搜索字典json
}

type GenerallyListResp struct {
	GenerallyResp
	Total int64 `json:"total"`
}

type UserDetailReq struct {
}

type UserDetailResp struct {
}

type UserAuthListReq struct {
}

type UserAuthListResp struct {
}

type UpdateUserDetailReq struct {
}

type UpdateUserDetailResp struct {
}

type UpdateUserPasswordReq struct {
}

type UpdateUserPasswordResp struct {
}

type UpdateUserAvatarReq struct {
}

type UpdateUserAvatarResp struct {
}

type UserRetrievePasswordReq struct {
}

type UserRetrievePasswordResp struct {
}

type PreResultReq struct {
}

type PreResultResp struct {
}

type AddPreResultReq struct {
}

type AddPreResultResp struct {
}

type RemovePreResultReq struct {
}

type RemovePreResultResp struct {
}

type UserCompsReq struct {
}

type UserCompsResp struct {
}

type RegisterCompReq struct {
}

type RegisterCompResp struct {
}

type RegisterCompAddEventReq struct {
}

type RegisterCompAddEventResp struct {
}

type RegisterCompCallbackReq struct {
}

type RegisterCompCallbackResp struct {
}

type RetireCompReq struct {
}

type RetireCompResp struct {
}

type UserCompReq struct {
}

type UserCompResp struct {
}

type CreateOrganizersReq struct {
}

type CreateOrganizersResp struct {
}

type GetOrganizerReq struct {
}

type GetOrganizerResp struct {
}

type AddOrganizersPersonReq struct {
}

type AddOrganizersPersonResp struct {
}

type RemoveOrganizersPersonReq struct {
}

type RemoveOrganizersPersonResp struct {
}

type ExitOrganizersReq struct {
}

type ExitOrganizersResp struct {
}

type GetOrganizersReq struct {
}

type GetOrganizersResp struct {
}

type DeleteOrganizersReq struct {
}

type DeleteOrganizersResp struct {
}

type GetCompsReq struct {
}

type GetCompsResp struct {
}

type CreateCompReq struct {
}

type CreateCompResp struct {
}

type ApplyCompReq struct {
}

type ApplyCompResp struct {
}

type DeleteCompReq struct {
}

type DeleteCompResp struct {
}

type UpdateCompReq struct {
}

type UpdateCompResp struct {
}

type AddCompResultsReq struct {
}

type AddCompResultsResp struct {
}

type GetPreResultsReq struct {
}

type GetPreResultsResp struct {
}

type ApprovalPreResultsReq struct {
}

type ApprovalPreResultsResp struct {
}

type AddCompPlayerReq struct {
}

type AddCompPlayerResp struct {
}

type ApprovalCompsReq struct {
}

type ApprovalCompsResp struct {
}

type ApprovalCompReq struct {
}

type ApprovalCompResp struct {
}

type EventsReq struct {
}

type EventsResp struct {
}

type NotifyReq struct {
}

type NotifyResp struct {
}

type SwaggerReq struct {
}

type SwaggerResp struct {
}

type PlayersReq struct {
}

type PlayersResp struct {
}

type PlayerReq struct {
}

type PlayerResp struct {
}

type PlayerMonthlyReportReq struct {
}

type PlayerMonthlyReportResp struct {
}

type PlayerYearReportReq struct {
}

type PlayerYearReportResp struct {
}

type PlayerResultReq struct {
}

type PlayerResultResp struct {
}

type PlayerNemesisReq struct {
}

type PlayerNemesisResp struct {
}

type PlayerRecordsReq struct {
}

type PlayerRecordsResp struct {
}

type PlayerSorReq struct {
}

type PlayerSorResp struct {
}

type CompetitionReq struct {
}

type CompetitionResp struct {
}

type CompetitionsReq struct {
}

type CompetitionsResp struct {
}

type CompetitionRegistersReq struct {
}

type CompetitionRegistersResp struct {
}

type CompetitionResultsReq struct {
}

type CompetitionResultsResp struct {
}

type CompetitionRecordReq struct {
}

type CompetitionRecordResp struct {
}

type SumOfRanksReq struct {
}

type SumOfRanksResp struct {
}

type MedalCollectionReq struct {
}

type MedalCollectionResp struct {
}

type TopNReq struct {
}

type TopNResp struct {
}

type RecordNumReq struct {
}

type RecordNumResp struct {
}

type CompRecordNumReq struct {
}

type CompRecordNumResp struct {
}

type RecordWithTimeReq struct {
}

type RecordWithTimeResp struct {
}

type RecordsReq struct {
}

type RecordsResp struct {
}

type SorReq struct {
}

type SorResp struct {
}

type BestResultReq struct {
}

type BestResultResp struct {
}

type CreateEventReq struct {
}

type CreateEventResp struct {
}

type RemoveEventReq struct {
}

type RemoveEventResp struct {
}

type UpdateEventReq struct {
}

type UpdateEventResp struct {
}

type UpdateNameReq struct {
}

type UpdateNameResp struct {
}

type UpdateFooterReq struct {
}

type UpdateFooterResp struct {
}

type UpdateLogoReq struct {
}

type UpdateLogoResp struct {
}

type CreateNotifyReq struct {
}

type CreateNotifyResp struct {
}

type RemoveNotifyReq struct {
}

type RemoveNotifyResp struct {
}

type UpdateNotifyReq struct {
}

type UpdateNotifyResp struct {
}

type TopNotifyReq struct {
}

type TopNotifyResp struct {
}

type FixedNotifyReq struct {
}

type FixedNotifyResp struct {
}

type PostsReq struct {
}

type PostsResp struct {
}

type PostReq struct {
}

type PostResp struct {
}

type CreatePostReq struct {
}

type CreatePostResp struct {
}

type UpdatePostReq struct {
}

type UpdatePostResp struct {
}

type DeletePostReq struct {
}

type DeletePostResp struct {
}

type CommentsReq struct {
}

type CommentsResp struct {
}

type CreateCommentReq struct {
}

type CreateCommentResp struct {
}

type DeleteCommentReq struct {
}

type DeleteCommentResp struct {
}

type ReplyCommentReq struct {
}

type ReplyCommentResp struct {
}
