// Code generated by goctl. DO NOT EDIT.
package types

type AuthCodeReq struct {
	Ip string `json:"ip"`
}

type AuthCodeResp struct {
	GenerallyResp
	Timeout   int64  `json:"timeout"`
	MdCode    string `json:"mdCode"`
	CodeImage string `json:"codeImage"` // base64
}

type LoginReq struct {
	UserName  string `json:"userName"`  // 用户名
	Password  string `json:"password"`  // 密码
	Timestamp int64  `json:"timestamp"` // 客户端时间戳
	Ip        string `json:"ip"`        // Ip地址
	MdCode    string `json:"mdCode"`    // 获取校验码的数据
	AuthCode  string `json:"authCode"`  // 验证码
}

type LoginResp struct {
	GenerallyResp
	Refresh string `json:"refresh"`
	Token   string `json:"token"`
	Timeout int64  `json:"timeout"`
}

type RegisterReq struct {
	LoginReq
	MyID    string `json:"myId"`
	LoginID string `json:"loginId"`
	QQ      string `json:"qq"`
}

type RegisterResp struct {
	GenerallyResp
	Refresh string `json:"refresh"` // 长期刷新秘钥
	Token   string `json:"token"`
	Timeout int64  `json:"timeout"`
}

type RefreshToeknReq struct {
	Refresh string `json:"refresh"`
}

type RefreshToeknResp struct {
	Token   string `json:"token"`
	Timeout int64  `json:"timeout"`
}

type RoleListReq struct {
}

type RoleListResp struct {
}

type CreateRoleReq struct {
}

type CreateRoleResp struct {
}

type DeleteRoleReq struct {
}

type DeleteRoleResp struct {
}

type UpdateRoleReq struct {
}

type UpdateRoleResp struct {
}

type BindRoleReq struct {
}

type BindRoleResp struct {
}

type UnbindRoleReq struct {
}

type UnbindRoleResp struct {
}

type RoleRulesReq struct {
}

type RoleRulesResp struct {
}

type AddRulesReq struct {
}

type AddRulesResp struct {
}

type DeleteRulesReq struct {
}

type DeleteRulesResp struct {
}

type UpdateRulesReq struct {
}

type UpdateRulesResp struct {
}

type GenerallyStrIdReq struct {
	ID string `path:"id"`
}

type GenerallyResp struct {
	Message string `json:"message"`
	Status  string `json:"status"`
	Code    int64  `json:"code"`
}

type GenerallyListReq struct {
	Page int64 `form:"page"`
	Size int64 `form:"size"`
}

type GenerallyListResp struct {
	GenerallyResp
	Total int64 `json:"total"`
}

type UserDetailReq struct {
}

type UserDetailResp struct {
}

type UserAuthListReq struct {
}

type UserAuthListResp struct {
}

type UpdateUserDetailReq struct {
}

type UpdateUserDetailResp struct {
}

type UpdateUserPasswordReq struct {
}

type UpdateUserPasswordResp struct {
}

type UpdateUserAvatarReq struct {
}

type UpdateUserAvatarResp struct {
}

type UserRetrievePasswordReq struct {
}

type UserRetrievePasswordResp struct {
}

type PreResultReq struct {
}

type PreResultResp struct {
}

type AddPreResultReq struct {
}

type AddPreResultResp struct {
}

type RemovePreResultReq struct {
}

type RemovePreResultResp struct {
}

type UserCompsReq struct {
}

type UserCompsResp struct {
}

type RegisterCompReq struct {
}

type RegisterCompResp struct {
}

type RegisterCompAddEventReq struct {
}

type RegisterCompAddEventResp struct {
}

type RegisterCompCallbackReq struct {
}

type RegisterCompCallbackResp struct {
}

type RetireCompReq struct {
}

type RetireCompResp struct {
}

type UserCompReq struct {
}

type UserCompResp struct {
}

type CreateOrganizersReq struct {
}

type CreateOrganizersResp struct {
}

type GetOrganizerReq struct {
}

type GetOrganizerResp struct {
}

type AddOrganizersPersonReq struct {
}

type AddOrganizersPersonResp struct {
}

type RemoveOrganizersPersonReq struct {
}

type RemoveOrganizersPersonResp struct {
}

type ExitOrganizersReq struct {
}

type ExitOrganizersResp struct {
}

type GetOrganizersReq struct {
}

type GetOrganizersResp struct {
}

type DeleteOrganizersReq struct {
}

type DeleteOrganizersResp struct {
}

type GetCompsReq struct {
}

type GetCompsResp struct {
}

type CreateCompReq struct {
}

type CreateCompResp struct {
}

type ApplyCompReq struct {
}

type ApplyCompResp struct {
}

type DeleteCompReq struct {
}

type DeleteCompResp struct {
}

type UpdateCompReq struct {
}

type UpdateCompResp struct {
}

type AddCompResultsReq struct {
}

type AddCompResultsResp struct {
}

type GetPreResultsReq struct {
}

type GetPreResultsResp struct {
}

type ApprovalPreResultsReq struct {
}

type ApprovalPreResultsResp struct {
}

type AddCompPlayerReq struct {
}

type AddCompPlayerResp struct {
}

type ApprovalCompsReq struct {
}

type ApprovalCompsResp struct {
}

type ApprovalCompReq struct {
}

type ApprovalCompResp struct {
}

type EventsReq struct {
}

type EventsResp struct {
}

type NotifyReq struct {
}

type NotifyResp struct {
}

type PlayersReq struct {
}

type PlayersResp struct {
}

type PlayerReq struct {
}

type PlayerResp struct {
}

type PlayerMonthlyReportReq struct {
}

type PlayerMonthlyReportResp struct {
}

type PlayerYearReportReq struct {
}

type PlayerYearReportResp struct {
}

type PlayerResultReq struct {
}

type PlayerResultResp struct {
}

type PlayerNemesisReq struct {
}

type PlayerNemesisResp struct {
}

type PlayerRecordsReq struct {
}

type PlayerRecordsResp struct {
}

type PlayerSorReq struct {
}

type PlayerSorResp struct {
}

type CompetitionReq struct {
}

type CompetitionResp struct {
}

type CompetitionsReq struct {
}

type CompetitionsResp struct {
}

type CompetitionRegistersReq struct {
}

type CompetitionRegistersResp struct {
}

type CompetitionResultsReq struct {
}

type CompetitionResultsResp struct {
}

type CompetitionRecordReq struct {
}

type CompetitionRecordResp struct {
}

type SumOfRanksReq struct {
}

type SumOfRanksResp struct {
}

type MedalCollectionReq struct {
}

type MedalCollectionResp struct {
}

type TopNReq struct {
}

type TopNResp struct {
}

type RecordNumReq struct {
}

type RecordNumResp struct {
}

type CompRecordNumReq struct {
}

type CompRecordNumResp struct {
}

type RecordWithTimeReq struct {
}

type RecordWithTimeResp struct {
}

type RecordsReq struct {
}

type RecordsResp struct {
}

type SorReq struct {
}

type SorResp struct {
}

type BestResultReq struct {
}

type BestResultResp struct {
}

type CreateEventReq struct {
}

type CreateEventResp struct {
}

type RemoveEventReq struct {
}

type RemoveEventResp struct {
}

type UpdateEventReq struct {
}

type UpdateEventResp struct {
}

type UpdateNameReq struct {
}

type UpdateNameResp struct {
}

type UpdateFooterReq struct {
}

type UpdateFooterResp struct {
}

type UpdateLogoReq struct {
}

type UpdateLogoResp struct {
}

type CreateNotifyReq struct {
}

type CreateNotifyResp struct {
}

type RemoveNotifyReq struct {
}

type RemoveNotifyResp struct {
}

type UpdateNotifyReq struct {
}

type UpdateNotifyResp struct {
}

type TopNotifyReq struct {
}

type TopNotifyResp struct {
}

type FixedNotifyReq struct {
	GenerallyStrIdReq
}

type FixedNotifyResp struct {
}

type PostsReq struct {
}

type PostsResp struct {
}

type PostReq struct {
}

type PostResp struct {
}

type CreatePostReq struct {
}

type CreatePostResp struct {
}

type UpdatePostReq struct {
}

type UpdatePostResp struct {
}

type DeletePostReq struct {
}

type DeletePostResp struct {
}

type CommentsReq struct {
}

type CommentsResp struct {
}

type CreateCommentReq struct {
}

type CreateCommentResp struct {
}

type DeleteCommentReq struct {
}

type DeleteCommentResp struct {
}

type ReplyCommentReq struct {
}

type ReplyCommentResp struct {
}
